baseURL = "https://ean7.top/"
title = "Ean7的小站"
theme = "PaperMod"
languageCode = "zh-cn"

enableGitInfo = true

[pagination]
  pagerSize = 10

[params]
  comments = true
  env = "production"

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowToc = true
  ShowWordCount = true
  ShowLastMod = true


  defaultTheme = "auto"

  # 启用搜索
  fuseOpts = { isCaseSensitive = false, shouldSort = true }

# 必须：启用搜索
[outputs]
  home = ["HTML", "RSS", "JSON"]

[frontmatter]
  lastmod = ["lastmod", "modified", ":git", ":fileModTime", "date"]
[[menu.main]]
  name = "博客"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 2

[[menu.main]]
  name = "项目"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 4
  
[[menu.main]]
  name = "🔍"
  url = "/search/"
  weight = 5